//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CprSoap.CprService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/", ConfigurationName="CprService.PersonBasicInformationService_1_portType")]
    internal interface PersonBasicInformationService_1_portType {
        
        // CODEGEN: Generating message contract since the operation PersonBasicInformationService_1_operation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/axis2/services/PersonBasicInformationService_2/Input", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CprSoap.CprService.OperationOutput PersonBasicInformationService_1_operation(CprSoap.CprService.OperationInput request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public partial class PersonBasicInformationResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PersonBasicInformationStructureType personBasicInformationStructureField;
        
        private ReturnStructureType returnStructureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PersonBasicInformationStructureType PersonBasicInformationStructure {
            get {
                return this.personBasicInformationStructureField;
            }
            set {
                this.personBasicInformationStructureField = value;
                this.RaisePropertyChanged("PersonBasicInformationStructure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReturnStructureType ReturnStructure {
            get {
                return this.returnStructureField;
            }
            set {
                this.returnStructureField = value;
                this.RaisePropertyChanged("ReturnStructure");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public partial class PersonBasicInformationStructureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string personCivilRegistrationIdentifierField;
        
        private string addresseeNameField;
        
        private PersonBirthDateStructureType personBirthDateStructureField;
        
        private PersonGenderCodeType personGenderCodeField;
        
        private PersonStatusCodeType personStatusCodeField;
        
        private PersonDeathDateStructureType personDeathDateStructureField;
        
        private PersonCivilRegistrationStatusIdentifierCodeStructureType personCivilRegistrationIdentifierCodeStructureField;
        
        private string personCivilRegistrationCurrentIdentifierField;
        
        private AddressIdentifierCodeType addressIdentifierCodeField;
        
        private bool addressIdentifierCodeFieldSpecified;
        
        private object itemField;
        
        private bool personInformationProtectionIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=0)]
        public string PersonCivilRegistrationIdentifier {
            get {
                return this.personCivilRegistrationIdentifierField;
            }
            set {
                this.personCivilRegistrationIdentifierField = value;
                this.RaisePropertyChanged("PersonCivilRegistrationIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/05/19/", Order=1)]
        public string AddresseeName {
            get {
                return this.addresseeNameField;
            }
            set {
                this.addresseeNameField = value;
                this.RaisePropertyChanged("AddresseeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/11/24/", Order=2)]
        public PersonBirthDateStructureType PersonBirthDateStructure {
            get {
                return this.personBirthDateStructureField;
            }
            set {
                this.personBirthDateStructureField = value;
                this.RaisePropertyChanged("PersonBirthDateStructure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/23/", Order=3)]
        public PersonGenderCodeType PersonGenderCode {
            get {
                return this.personGenderCodeField;
            }
            set {
                this.personGenderCodeField = value;
                this.RaisePropertyChanged("PersonGenderCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public PersonStatusCodeType PersonStatusCode {
            get {
                return this.personStatusCodeField;
            }
            set {
                this.personStatusCodeField = value;
                this.RaisePropertyChanged("PersonStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public PersonDeathDateStructureType PersonDeathDateStructure {
            get {
                return this.personDeathDateStructureField;
            }
            set {
                this.personDeathDateStructureField = value;
                this.RaisePropertyChanged("PersonDeathDateStructure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public PersonCivilRegistrationStatusIdentifierCodeStructureType PersonCivilRegistrationIdentifierCodeStructure {
            get {
                return this.personCivilRegistrationIdentifierCodeStructureField;
            }
            set {
                this.personCivilRegistrationIdentifierCodeStructureField = value;
                this.RaisePropertyChanged("PersonCivilRegistrationIdentifierCodeStructure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PersonCivilRegistrationCurrentIdentifier {
            get {
                return this.personCivilRegistrationCurrentIdentifierField;
            }
            set {
                this.personCivilRegistrationCurrentIdentifierField = value;
                this.RaisePropertyChanged("PersonCivilRegistrationCurrentIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public AddressIdentifierCodeType AddressIdentifierCode {
            get {
                return this.addressIdentifierCodeField;
            }
            set {
                this.addressIdentifierCodeField = value;
                this.RaisePropertyChanged("AddressIdentifierCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressIdentifierCodeSpecified {
            get {
                return this.addressIdentifierCodeFieldSpecified;
            }
            set {
                this.addressIdentifierCodeFieldSpecified = value;
                this.RaisePropertyChanged("AddressIdentifierCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DanishAddressStructure", typeof(DanishAddressStructureType), Order=9)]
        [System.Xml.Serialization.XmlElementAttribute("ForeignAddressStructure", typeof(ForeignAddressStructureType), Order=9)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/11/24/", Order=10)]
        public bool PersonInformationProtectionIndicator {
            get {
                return this.personInformationProtectionIndicatorField;
            }
            set {
                this.personInformationProtectionIndicatorField = value;
                this.RaisePropertyChanged("PersonInformationProtectionIndicator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/11/24/")]
    public partial class PersonBirthDateStructureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime birthDateField;
        
        private bool birthDateUncertaintyIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", DataType="date", Order=0)]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool BirthDateUncertaintyIndicator {
            get {
                return this.birthDateUncertaintyIndicatorField;
            }
            set {
                this.birthDateUncertaintyIndicatorField = value;
                this.RaisePropertyChanged("BirthDateUncertaintyIndicator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public partial class ReturnStructureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnCodeField;
        
        private string returnMessageTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReturnMessageText {
            get {
                return this.returnMessageTextField;
            }
            set {
                this.returnMessageTextField = value;
                this.RaisePropertyChanged("ReturnMessageText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public partial class ForeignAddressStructureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string postalAddressFirstLineTextField;
        
        private string postalAddressSecondLineTextField;
        
        private string postalAddressThirdLineTextField;
        
        private string postalAddressFourthLineTextField;
        
        private string postalAddressFifthLineTextField;
        
        private CountryIdentificationCodeType countryIdentificationCodeField;
        
        private string locationDescriptionTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/", Order=0)]
        public string PostalAddressFirstLineText {
            get {
                return this.postalAddressFirstLineTextField;
            }
            set {
                this.postalAddressFirstLineTextField = value;
                this.RaisePropertyChanged("PostalAddressFirstLineText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/", Order=1)]
        public string PostalAddressSecondLineText {
            get {
                return this.postalAddressSecondLineTextField;
            }
            set {
                this.postalAddressSecondLineTextField = value;
                this.RaisePropertyChanged("PostalAddressSecondLineText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/", Order=2)]
        public string PostalAddressThirdLineText {
            get {
                return this.postalAddressThirdLineTextField;
            }
            set {
                this.postalAddressThirdLineTextField = value;
                this.RaisePropertyChanged("PostalAddressThirdLineText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/", Order=3)]
        public string PostalAddressFourthLineText {
            get {
                return this.postalAddressFourthLineTextField;
            }
            set {
                this.postalAddressFourthLineTextField = value;
                this.RaisePropertyChanged("PostalAddressFourthLineText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/", Order=4)]
        public string PostalAddressFifthLineText {
            get {
                return this.postalAddressFifthLineTextField;
            }
            set {
                this.postalAddressFifthLineTextField = value;
                this.RaisePropertyChanged("PostalAddressFifthLineText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=5)]
        public CountryIdentificationCodeType CountryIdentificationCode {
            get {
                return this.countryIdentificationCodeField;
            }
            set {
                this.countryIdentificationCodeField = value;
                this.RaisePropertyChanged("CountryIdentificationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/capevo.dk/xml/schemas/2007/08/01/", Order=6)]
        public string LocationDescriptionText {
            get {
                return this.locationDescriptionTextField;
            }
            set {
                this.locationDescriptionTextField = value;
                this.RaisePropertyChanged("LocationDescriptionText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public partial class CountryIdentificationCodeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _CountryIdentificationSchemeType schemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public _CountryIdentificationSchemeType scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
                this.RaisePropertyChanged("scheme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public enum _CountryIdentificationSchemeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha2")]
        iso3166alpha2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha3")]
        iso3166alpha3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("un-numeric3")]
        unnumeric3,
        
        /// <remarks/>
        imk,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2006/01/10/")]
    public partial class CompletePostalLabelType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addresseeNameField;
        
        private string postalAddressFirstLineTextField;
        
        private string postalAddressSecondLineTextField;
        
        private string postalAddressThirdLineTextField;
        
        private string postalAddressFourthLineTextField;
        
        private string postalAddressFifthLineTextField;
        
        private string postalAddressSixthLineTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/05/19/", Order=0)]
        public string AddresseeName {
            get {
                return this.addresseeNameField;
            }
            set {
                this.addresseeNameField = value;
                this.RaisePropertyChanged("AddresseeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/", Order=1)]
        public string PostalAddressFirstLineText {
            get {
                return this.postalAddressFirstLineTextField;
            }
            set {
                this.postalAddressFirstLineTextField = value;
                this.RaisePropertyChanged("PostalAddressFirstLineText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/", Order=2)]
        public string PostalAddressSecondLineText {
            get {
                return this.postalAddressSecondLineTextField;
            }
            set {
                this.postalAddressSecondLineTextField = value;
                this.RaisePropertyChanged("PostalAddressSecondLineText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/", Order=3)]
        public string PostalAddressThirdLineText {
            get {
                return this.postalAddressThirdLineTextField;
            }
            set {
                this.postalAddressThirdLineTextField = value;
                this.RaisePropertyChanged("PostalAddressThirdLineText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/", Order=4)]
        public string PostalAddressFourthLineText {
            get {
                return this.postalAddressFourthLineTextField;
            }
            set {
                this.postalAddressFourthLineTextField = value;
                this.RaisePropertyChanged("PostalAddressFourthLineText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/", Order=5)]
        public string PostalAddressFifthLineText {
            get {
                return this.postalAddressFifthLineTextField;
            }
            set {
                this.postalAddressFifthLineTextField = value;
                this.RaisePropertyChanged("PostalAddressFifthLineText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/", Order=6)]
        public string PostalAddressSixthLineText {
            get {
                return this.postalAddressSixthLineTextField;
            }
            set {
                this.postalAddressSixthLineTextField = value;
                this.RaisePropertyChanged("PostalAddressSixthLineText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public partial class AddressNotCompleteType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string municipalityCodeField;
        
        private string streetCodeField;
        
        private string mailDeliverySublocationIdentifierField;
        
        private string streetNameField;
        
        private string streetNameForAddressingNameField;
        
        private string streetBuildingIdentifierField;
        
        private string greenlandBuildingIdentifierField;
        
        private string suiteIdentifierField;
        
        private string floorIdentifierField;
        
        private string districtSubdivisionIdentifierField;
        
        private string postCodeIdentifierField;
        
        private string districtNameField;
        
        private CountryIdentificationCodeType countryIdentificationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=0)]
        public string MunicipalityCode {
            get {
                return this.municipalityCodeField;
            }
            set {
                this.municipalityCodeField = value;
                this.RaisePropertyChanged("MunicipalityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=1)]
        public string StreetCode {
            get {
                return this.streetCodeField;
            }
            set {
                this.streetCodeField = value;
                this.RaisePropertyChanged("StreetCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=2)]
        public string MailDeliverySublocationIdentifier {
            get {
                return this.mailDeliverySublocationIdentifierField;
            }
            set {
                this.mailDeliverySublocationIdentifierField = value;
                this.RaisePropertyChanged("MailDeliverySublocationIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=3)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=4)]
        public string StreetNameForAddressingName {
            get {
                return this.streetNameForAddressingNameField;
            }
            set {
                this.streetNameForAddressingNameField = value;
                this.RaisePropertyChanged("StreetNameForAddressingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=5)]
        public string StreetBuildingIdentifier {
            get {
                return this.streetBuildingIdentifierField;
            }
            set {
                this.streetBuildingIdentifierField = value;
                this.RaisePropertyChanged("StreetBuildingIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string GreenlandBuildingIdentifier {
            get {
                return this.greenlandBuildingIdentifierField;
            }
            set {
                this.greenlandBuildingIdentifierField = value;
                this.RaisePropertyChanged("GreenlandBuildingIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=7)]
        public string SuiteIdentifier {
            get {
                return this.suiteIdentifierField;
            }
            set {
                this.suiteIdentifierField = value;
                this.RaisePropertyChanged("SuiteIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=8)]
        public string FloorIdentifier {
            get {
                return this.floorIdentifierField;
            }
            set {
                this.floorIdentifierField = value;
                this.RaisePropertyChanged("FloorIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=9)]
        public string DistrictSubdivisionIdentifier {
            get {
                return this.districtSubdivisionIdentifierField;
            }
            set {
                this.districtSubdivisionIdentifierField = value;
                this.RaisePropertyChanged("DistrictSubdivisionIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=10)]
        public string PostCodeIdentifier {
            get {
                return this.postCodeIdentifierField;
            }
            set {
                this.postCodeIdentifierField = value;
                this.RaisePropertyChanged("PostCodeIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=11)]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
                this.RaisePropertyChanged("DistrictName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=12)]
        public CountryIdentificationCodeType CountryIdentificationCode {
            get {
                return this.countryIdentificationCodeField;
            }
            set {
                this.countryIdentificationCodeField = value;
                this.RaisePropertyChanged("CountryIdentificationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public partial class AddressCompleteGreenlandType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string municipalityCodeField;
        
        private string streetCodeField;
        
        private string mailDeliverySublocationIdentifierField;
        
        private string streetNameField;
        
        private string streetNameForAddressingNameField;
        
        private string streetBuildingIdentifierField;
        
        private string greenlandBuildingIdentifierField;
        
        private string suiteIdentifierField;
        
        private string floorIdentifierField;
        
        private string districtSubdivisionIdentifierField;
        
        private string postCodeIdentifierField;
        
        private string districtNameField;
        
        private CountryIdentificationCodeType countryIdentificationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=0)]
        public string MunicipalityCode {
            get {
                return this.municipalityCodeField;
            }
            set {
                this.municipalityCodeField = value;
                this.RaisePropertyChanged("MunicipalityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=1)]
        public string StreetCode {
            get {
                return this.streetCodeField;
            }
            set {
                this.streetCodeField = value;
                this.RaisePropertyChanged("StreetCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=2)]
        public string MailDeliverySublocationIdentifier {
            get {
                return this.mailDeliverySublocationIdentifierField;
            }
            set {
                this.mailDeliverySublocationIdentifierField = value;
                this.RaisePropertyChanged("MailDeliverySublocationIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=3)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=4)]
        public string StreetNameForAddressingName {
            get {
                return this.streetNameForAddressingNameField;
            }
            set {
                this.streetNameForAddressingNameField = value;
                this.RaisePropertyChanged("StreetNameForAddressingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=5)]
        public string StreetBuildingIdentifier {
            get {
                return this.streetBuildingIdentifierField;
            }
            set {
                this.streetBuildingIdentifierField = value;
                this.RaisePropertyChanged("StreetBuildingIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string GreenlandBuildingIdentifier {
            get {
                return this.greenlandBuildingIdentifierField;
            }
            set {
                this.greenlandBuildingIdentifierField = value;
                this.RaisePropertyChanged("GreenlandBuildingIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=7)]
        public string SuiteIdentifier {
            get {
                return this.suiteIdentifierField;
            }
            set {
                this.suiteIdentifierField = value;
                this.RaisePropertyChanged("SuiteIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=8)]
        public string FloorIdentifier {
            get {
                return this.floorIdentifierField;
            }
            set {
                this.floorIdentifierField = value;
                this.RaisePropertyChanged("FloorIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=9)]
        public string DistrictSubdivisionIdentifier {
            get {
                return this.districtSubdivisionIdentifierField;
            }
            set {
                this.districtSubdivisionIdentifierField = value;
                this.RaisePropertyChanged("DistrictSubdivisionIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=10)]
        public string PostCodeIdentifier {
            get {
                return this.postCodeIdentifierField;
            }
            set {
                this.postCodeIdentifierField = value;
                this.RaisePropertyChanged("PostCodeIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=11)]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
                this.RaisePropertyChanged("DistrictName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=12)]
        public CountryIdentificationCodeType CountryIdentificationCode {
            get {
                return this.countryIdentificationCodeField;
            }
            set {
                this.countryIdentificationCodeField = value;
                this.RaisePropertyChanged("CountryIdentificationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/01/06/")]
    public partial class AddressPostalType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mailDeliverySublocationIdentifierField;
        
        private string streetNameField;
        
        private string streetNameForAddressingNameField;
        
        private string streetBuildingIdentifierField;
        
        private string floorIdentifierField;
        
        private string suiteIdentifierField;
        
        private string districtSubdivisionIdentifierField;
        
        private string postOfficeBoxIdentifierField;
        
        private string postCodeIdentifierField;
        
        private string districtNameField;
        
        private CountryIdentificationCodeType countryIdentificationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=0)]
        public string MailDeliverySublocationIdentifier {
            get {
                return this.mailDeliverySublocationIdentifierField;
            }
            set {
                this.mailDeliverySublocationIdentifierField = value;
                this.RaisePropertyChanged("MailDeliverySublocationIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=1)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=2)]
        public string StreetNameForAddressingName {
            get {
                return this.streetNameForAddressingNameField;
            }
            set {
                this.streetNameForAddressingNameField = value;
                this.RaisePropertyChanged("StreetNameForAddressingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=3)]
        public string StreetBuildingIdentifier {
            get {
                return this.streetBuildingIdentifierField;
            }
            set {
                this.streetBuildingIdentifierField = value;
                this.RaisePropertyChanged("StreetBuildingIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=4)]
        public string FloorIdentifier {
            get {
                return this.floorIdentifierField;
            }
            set {
                this.floorIdentifierField = value;
                this.RaisePropertyChanged("FloorIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=5)]
        public string SuiteIdentifier {
            get {
                return this.suiteIdentifierField;
            }
            set {
                this.suiteIdentifierField = value;
                this.RaisePropertyChanged("SuiteIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=6)]
        public string DistrictSubdivisionIdentifier {
            get {
                return this.districtSubdivisionIdentifierField;
            }
            set {
                this.districtSubdivisionIdentifierField = value;
                this.RaisePropertyChanged("DistrictSubdivisionIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/13/", DataType="integer", Order=7)]
        public string PostOfficeBoxIdentifier {
            get {
                return this.postOfficeBoxIdentifierField;
            }
            set {
                this.postOfficeBoxIdentifierField = value;
                this.RaisePropertyChanged("PostOfficeBoxIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=8)]
        public string PostCodeIdentifier {
            get {
                return this.postCodeIdentifierField;
            }
            set {
                this.postCodeIdentifierField = value;
                this.RaisePropertyChanged("PostCodeIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=9)]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
                this.RaisePropertyChanged("DistrictName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=10)]
        public CountryIdentificationCodeType CountryIdentificationCode {
            get {
                return this.countryIdentificationCodeField;
            }
            set {
                this.countryIdentificationCodeField = value;
                this.RaisePropertyChanged("CountryIdentificationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2005/03/15/")]
    public partial class AddressAccessType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string municipalityCodeField;
        
        private string streetCodeField;
        
        private string streetBuildingIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=0)]
        public string MunicipalityCode {
            get {
                return this.municipalityCodeField;
            }
            set {
                this.municipalityCodeField = value;
                this.RaisePropertyChanged("MunicipalityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=1)]
        public string StreetCode {
            get {
                return this.streetCodeField;
            }
            set {
                this.streetCodeField = value;
                this.RaisePropertyChanged("StreetCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=2)]
        public string StreetBuildingIdentifier {
            get {
                return this.streetBuildingIdentifierField;
            }
            set {
                this.streetBuildingIdentifierField = value;
                this.RaisePropertyChanged("StreetBuildingIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/01/06/")]
    public partial class AddressCompleteType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddressAccessType addressAccessField;
        
        private AddressPostalType addressPostalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2005/03/15/", Order=0)]
        public AddressAccessType AddressAccess {
            get {
                return this.addressAccessField;
            }
            set {
                this.addressAccessField = value;
                this.RaisePropertyChanged("AddressAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AddressPostalType AddressPostal {
            get {
                return this.addressPostalField;
            }
            set {
                this.addressPostalField = value;
                this.RaisePropertyChanged("AddressPostal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public partial class DanishAddressStructureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddressStatusCodeType addressStatusCodeField;
        
        private string municipalityNameField;
        
        private string careOfNameField;
        
        private object itemField;
        
        private CompletePostalLabelType completePostalLabelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AddressStatusCodeType AddressStatusCode {
            get {
                return this.addressStatusCodeField;
            }
            set {
                this.addressStatusCodeField = value;
                this.RaisePropertyChanged("AddressStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2006/05/23/", Order=1)]
        public string MunicipalityName {
            get {
                return this.municipalityNameField;
            }
            set {
                this.municipalityNameField = value;
                this.RaisePropertyChanged("MunicipalityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/itst.dk/xml/schemas/2005/06/24/", Order=2)]
        public string CareOfName {
            get {
                return this.careOfNameField;
            }
            set {
                this.careOfNameField = value;
                this.RaisePropertyChanged("CareOfName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressCompleteGreenland", typeof(AddressCompleteGreenlandType), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("AddressNotComplete", typeof(AddressNotCompleteType), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("AddressComplete", typeof(AddressCompleteType), Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/01/06/", Order=3)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2006/01/10/", Order=4)]
        public CompletePostalLabelType CompletePostalLabel {
            get {
                return this.completePostalLabelField;
            }
            set {
                this.completePostalLabelField = value;
                this.RaisePropertyChanged("CompletePostalLabel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public enum AddressStatusCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public partial class PersonCivilRegistrationStatusIdentifierCodeStructureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PersonCivilRegistrationIdentifierCodeType personCivilRegistrationIdentifierStatusCodeField;
        
        private PersonCivilRegistrationIdentifierReasonsCodeType personCivilRegistrationIdentifierReasonsCodeField;
        
        private bool personCivilRegistrationIdentifierReasonsCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PersonCivilRegistrationIdentifierCodeType PersonCivilRegistrationIdentifierStatusCode {
            get {
                return this.personCivilRegistrationIdentifierStatusCodeField;
            }
            set {
                this.personCivilRegistrationIdentifierStatusCodeField = value;
                this.RaisePropertyChanged("PersonCivilRegistrationIdentifierStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PersonCivilRegistrationIdentifierReasonsCodeType PersonCivilRegistrationIdentifierReasonsCode {
            get {
                return this.personCivilRegistrationIdentifierReasonsCodeField;
            }
            set {
                this.personCivilRegistrationIdentifierReasonsCodeField = value;
                this.RaisePropertyChanged("PersonCivilRegistrationIdentifierReasonsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonCivilRegistrationIdentifierReasonsCodeSpecified {
            get {
                return this.personCivilRegistrationIdentifierReasonsCodeFieldSpecified;
            }
            set {
                this.personCivilRegistrationIdentifierReasonsCodeFieldSpecified = value;
                this.RaisePropertyChanged("PersonCivilRegistrationIdentifierReasonsCodeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public enum PersonCivilRegistrationIdentifierCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public enum PersonCivilRegistrationIdentifierReasonsCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("60")]
        Item60,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public partial class PersonDeathDateStructureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime personDeathDateField;
        
        private bool personDeathDateUncertaintyIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime PersonDeathDate {
            get {
                return this.personDeathDateField;
            }
            set {
                this.personDeathDateField = value;
                this.RaisePropertyChanged("PersonDeathDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool PersonDeathDateUncertaintyIndicator {
            get {
                return this.personDeathDateUncertaintyIndicatorField;
            }
            set {
                this.personDeathDateUncertaintyIndicatorField = value;
                this.RaisePropertyChanged("PersonDeathDateUncertaintyIndicator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/23/")]
    public enum PersonGenderCodeType {
        
        /// <remarks/>
        male,
        
        /// <remarks/>
        female,
        
        /// <remarks/>
        unspecified,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public enum PersonStatusCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/")]
    public enum AddressIdentifierCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class OperationInput {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/", Order=0)]
        public string PersonBasicInformationRequest;
        
        public OperationInput() {
        }
        
        public OperationInput(string PersonBasicInformationRequest) {
            this.PersonBasicInformationRequest = PersonBasicInformationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class OperationOutput {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2008/05/01/", Order=0)]
        public CprSoap.CprService.PersonBasicInformationResponseType PersonBasicInformationResponse;
        
        public OperationOutput() {
        }
        
        public OperationOutput(CprSoap.CprService.PersonBasicInformationResponseType PersonBasicInformationResponse) {
            this.PersonBasicInformationResponse = PersonBasicInformationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface PersonBasicInformationService_1_portTypeChannel : CprSoap.CprService.PersonBasicInformationService_1_portType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class PersonBasicInformationService_1_portTypeClient : System.ServiceModel.ClientBase<CprSoap.CprService.PersonBasicInformationService_1_portType>, CprSoap.CprService.PersonBasicInformationService_1_portType {
        
        public PersonBasicInformationService_1_portTypeClient() {
        }
        
        public PersonBasicInformationService_1_portTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonBasicInformationService_1_portTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonBasicInformationService_1_portTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonBasicInformationService_1_portTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CprSoap.CprService.OperationOutput CprSoap.CprService.PersonBasicInformationService_1_portType.PersonBasicInformationService_1_operation(CprSoap.CprService.OperationInput request) {
            return base.Channel.PersonBasicInformationService_1_operation(request);
        }
        
        public CprSoap.CprService.PersonBasicInformationResponseType PersonBasicInformationService_1_operation(string PersonBasicInformationRequest) {
            CprSoap.CprService.OperationInput inValue = new CprSoap.CprService.OperationInput();
            inValue.PersonBasicInformationRequest = PersonBasicInformationRequest;
            CprSoap.CprService.OperationOutput retVal = ((CprSoap.CprService.PersonBasicInformationService_1_portType)(this)).PersonBasicInformationService_1_operation(inValue);
            return retVal.PersonBasicInformationResponse;
        }
    }
}
